const test=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');const load=require('./load-ts.cjs');
const ids={user:'a1000000-0000-4000-8000-000000000001',company:'e1000000-0000-4000-8000-000000000001',visite:'f1000000-0000-4000-8000-000000000001',chantier:'c1000000-0000-4000-8000-000000000001',archive:'81000000-0000-4000-8000-000000000001',id:'83000000-0000-4000-8000-000000000001'};
const demande={id:ids.id,visiteId:ids.visite,auteurId:ids.user,archiveId:ids.archive,rapportReference:'rapport',precedentId:null,objet:'Rectification du constat',motif:'Erreur de transcription',contenu:'Le constat est précisé par cet avenant conservé après relecture.'};
const plan={id:ids.id,visite_id:ids.visite,auteur_id:ids.user,auteur_nom:'Inspecteur test',numero:1,archive_id:ids.archive,archive_sha256:'a'.repeat(64),objet:demande.objet,motif:demande.motif,contenu:demande.contenu,rapport_reference:'rapport',precedent_id:null,date_visite:'2026-09-14',valide_le:'2026-09-14T08:00:00Z',chantier_adresse:'Adresse fictive'};
function fixture(){const calls=[];let state={data:plan,error:null};const client={rpc:async(name,args)=>{calls.push([name,args]);return state;}};let publication=null,quota=true;const service={storage:{from:()=>({upload:async(path,bytes,opts)=>{assert.equal(opts.upsert,false);calls.push(['upload',path,bytes]);return{error:null};},remove:()=>{throw Error('Ne pas supprimer');}})},rpc:async(name,args)=>{calls.push([name,args]);return name==='consommer_quota'?{data:quota,error:null}:{data:publication?null:ids.id,error:publication};}};const mod=load('src/lib/supabase/avenant.ts',{'@react-pdf/renderer':{renderToBuffer:async()=>{calls.push(['render']);return Buffer.from('%PDF-test');}},'@/components/pdf/avenant-visite':{AvenantVisite:({plan})=>plan}});return{client,service,mod,calls,setState:x=>state=x,setPublication:x=>publication=x,setQuota:x=>quota=x};}
test('Avenant : demande normalisée, identifiants et longueurs contrôlés',()=>{const {validerDemandeAvenant}=load('src/lib/visites/avenant.ts');assert.equal(validerDemandeAvenant({...demande,objet:' '+demande.objet+' '}).objet,demande.objet);for(const patch of [{id:'invalide'},{auteurId:null},{precedentId:'invalide'},{contenu:'court'},{motif:'x'.repeat(1001)},{rapportReference:null}])assert.throws(()=>validerDemandeAvenant({...demande,...patch}));});
test('Avenant : publication d’un PDF neuf et rejeu reconnu sans nouvelle génération',async()=>{const f=fixture();const result=await f.mod.creerAvenant(f.client,f.service,demande,ids.chantier);assert.equal(result.id,ids.id);const upload=f.calls.find(c=>c[0]==='upload');assert.ok(upload[1].startsWith(`${ids.chantier}/visites/${ids.visite}/avenants/${ids.id}/`));assert.ok(upload[1].includes(createHash('sha256').update('%PDF-test').digest('hex')));const renders=f.calls.filter(c=>c[0]==='render').length;f.setState({data:{existant:{id:ids.id,numero:1}},error:null});assert.equal((await f.mod.creerAvenant(f.client,f.service,demande,ids.chantier)).dejaPublie,true);assert.equal(f.calls.filter(c=>c[0]==='render').length,renders);});
test('Avenant : conflit confirmé et panne réseau conservent une issue distincte',async()=>{for(const [code,refus] of [['40001',true],['NETWORK',false]]){const f=fixture();f.setPublication({code});await assert.rejects(f.mod.creerAvenant(f.client,f.service,demande,ids.chantier),e=>e.refusConfirme===refus);assert.equal(f.calls.filter(c=>c[0]==='upload').length,1);}const f=fixture();f.setQuota(null);await assert.rejects(f.mod.creerAvenant(f.client,f.service,demande,ids.chantier),e=>e.status===503);assert.equal(f.calls.some(c=>c[0]==='render'),false);});
test('Avenant : PDF téléchargé vérifié et chemin étranger refusé avant le réseau',async()=>{const {chargerPdfAvenant}=load('src/lib/supabase/avenant.ts');const bytes=Buffer.from('%PDF-fixture'),hash=createHash('sha256').update(bytes).digest('hex');const avenant={...plan,sha256:hash,storage_path:`${ids.chantier}/visites/${ids.visite}/avenants/${ids.id}/${hash}.pdf`};let calls=0,body=bytes;const client={storage:{from:()=>({download:()=>({asStream:async()=>{calls++;return{data:new ReadableStream({start(c){c.enqueue(body);c.close();}}),error:null};}})})}};assert.deepEqual(await chargerPdfAvenant(client,avenant,ids.chantier),bytes);body=Buffer.from('%PDF-altéré');await assert.rejects(chargerPdfAvenant(client,avenant,ids.chantier),/intégrité/);const before=calls;await assert.rejects(chargerPdfAvenant(client,{...avenant,storage_path:'base-documentaire/secret.pdf'},ids.chantier));assert.equal(calls,before);});
test('Avenants locaux : compte isolé, brouillon et demande incertaine conservés',()=>{const storage=new Map();const old=global.localStorage;global.localStorage={get length(){return storage.size},key:i=>[...storage.keys()][i]??null,getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)};try{const scope=load('src/lib/offline/scope.ts'),mod=load('src/lib/offline/avenant.ts',{'@/lib/offline/scope':scope});const own=scope.activateOfflineScope(ids.user,ids.company);const draft={id:ids.id,visiteId:ids.visite,userId:ids.user,entrepriseId:ids.company,objet:demande.objet,motif:demande.motif,contenu:demande.contenu,updatedAt:'2026-09-14',demande,publie:false};mod.sauverBrouillonAvenant(own,draft);assert.deepEqual(mod.lireBrouillonsAvenant(own,ids.visite)[0].demande,demande);const other=scope.activateOfflineScope('a2000000-0000-4000-8000-000000000001','e2000000-0000-4000-8000-000000000001');assert.equal(mod.lireBrouillonsAvenant(other,ids.visite).length,0);assert.throws(()=>mod.sauverBrouillonAvenant(own,draft));assert.throws(()=>mod.sauverBrouillonAvenant(other,draft));assert.equal(storage.size,1);}finally{global.localStorage=old;}});
test('Avenant API : compte différent refuse la publication avant service privilégié',async()=>{const {NextRequest}=require('next/server');const route=load('src/app/api/visites/[id]/avenants/route.ts',{'@/lib/supabase/server':{createClient:async()=>({}),createServiceClient:()=>{throw Error('Interdit');}},'@/lib/supabase/require-api-user':{requireApiUser:async()=>({user:{id:'autre'},response:null})}});const res=await route.POST(new NextRequest('https://app.test/api/avenants',{method:'POST',body:JSON.stringify(demande)}),{params:Promise.resolve({id:ids.visite})});assert.equal(res.status,409);});
test('Email : un avenant non relu bloque avant téléchargement et avant envoi',async()=>{
 const {NextRequest}=require('next/server');let sent=0,downloads=0;
 const visite={id:ids.visite,chantier_id:ids.chantier,rapport_url:'rapport'};
 const client={from:table=>{assert.equal(table,'visites');const q={select:()=>q,eq:()=>q,single:async()=>({data:visite,error:null})};return q;},storage:{from:()=>{downloads++;throw Error('Téléchargement prématuré');}}};
 const route=load('src/app/api/visites/[id]/email/route.ts',{'@/lib/supabase/server':{createClient:async()=>client},'@/lib/supabase/require-api-user':{requireApiUser:async()=>({user:{id:ids.user},response:null})},'@/lib/utils/security':{canAccessVisite:async()=>true,canAccessChantier:async()=>true,getUserRole:async()=> 'inspecteur'},'@/lib/roles/limites':{getLimits:()=>({canSendEmail:true})},'@/lib/rate-limit':{checkRateLimit:async()=>true},'@/lib/supabase/avenant':{...load('src/lib/supabase/avenant.ts'),lireAvenants:async()=>[{id:ids.id}]},'@/lib/email/send-rapport':{sendRapport:async()=>{sent++;}}});
 const response=await route.POST(new NextRequest('https://app.test/api/email',{method:'POST',body:JSON.stringify({rapportReference:'rapport',avenantsIds:[]})}),{params:Promise.resolve({id:ids.visite})});assert.equal(response.status,409);assert.equal(sent,0);assert.equal(downloads,0);
});
test('Email : le rapport et les avenants sont joints ensemble, taille totale bornée',async()=>{
 let calls=0,payload;
 const {sendRapport}=load('src/lib/email/send-rapport.ts',{'resend':{Resend:class{emails={send:async p=>{calls++;payload=p;return{data:{id:'fake'},error:null};}}}},'@/lib/env':{getResendApiKey:()=> 'test',getResendFromEmail:()=> 'test@example.test'}});
 const original=Buffer.from('%PDF-original'),annexe=Buffer.from('%PDF-annexe');
 await sendRapport(original,[{nom:'Recette',email:'test@example.test'}],'Adresse fictive','2026-09-14','Inspecteur fictif',null,[{filename:'avenant_1.pdf',content:annexe}]);
 assert.equal(calls,1);assert.equal(payload.attachments.length,2);assert.deepEqual(payload.attachments[0].content,original);assert.deepEqual(payload.attachments[1].content,annexe);assert.match(payload.html,/1 avenant/);
 await assert.rejects(sendRapport(Buffer.alloc(24*1024*1024),[{nom:'Recette',email:'test@example.test'}],'Adresse fictive','2026-09-14',undefined,null,[{filename:'avenant.pdf',content:Buffer.alloc(2*1024*1024)}]),/25 Mo/);assert.equal(calls,1);
});
