const test=require('node:test'),assert=require('node:assert/strict');
const {IDBFactory,IDBObjectStore}=require('fake-indexeddb');const load=require('./load-ts.cjs');
const user='a1000000-0000-4000-8000-000000000001',company='e1000000-0000-4000-8000-000000000001',ecart='b1000000-0000-4000-8000-000000000001';
function fixture(){global.indexedDB=new IDBFactory();const cache=new Map(),scopes=load('src/lib/offline/scope.ts',{},cache),scope=scopes.activateOfflineScope(user,company),mod=load('src/lib/offline/cycle.ts',{},cache);return{scope,scopes,mod};}
function draft(){return{id:crypto.randomUUID(),ecartId:ecart,auteurId:user,entrepriseId:company,updatedAt:new Date().toISOString(),responsable:'Entreprise test',echeance:'2026-09-20',commentaire:'Protection rétablie et vérifiée sur place.',baseRevision:1,pieces:[{id:crypto.randomUUID(),revision:1,file:new File([new Uint8Array([137,80,78,71,13,10,26,10,1,2,3])],'preuve.png',{type:'image/png'})}],pending:null,termine:false};}
test('Correction locale : réouverture conserve textes, octets, nom et UUID du fichier',async()=>{const {scope,mod}=fixture(),d=draft();await mod.sauverCycle(scope,d);const [r]=await mod.lireCycles(scope,ecart);assert.equal(r.commentaire,d.commentaire);assert.equal(r.pieces[0].file.name,'preuve.png');assert.equal(r.pieces[0].id,d.pieces[0].id);assert.deepEqual(await r.pieces[0].file.arrayBuffer(),await d.pieces[0].file.arrayBuffer());assert.equal((await mod.lireCycles(scope,crypto.randomUUID())).length,0);});
test('Correction locale : reprise d’une réponse perdue garde la demande exacte et sa révision',async()=>{const {scope,mod}=fixture(),d=draft();d.pending={operationId:crypto.randomUUID(),auteurId:user,entrepriseId:company,revision:1,action:'soumettre',responsable:d.responsable,echeance:d.echeance,commentaire:d.commentaire,pieces:[d.pieces[0].id]};await mod.sauverCycle(scope,d);const [r]=await mod.lireCycles(scope,ecart),copy=mod.copierCycle(r);assert.notEqual(copy.id,r.id);assert.deepEqual(copy.pending,d.pending);assert.equal(copy.baseRevision,1);await mod.sauverCycle(scope,copy);assert.equal((await mod.lireCycles(scope,ecart)).length,2);});
test('Correction locale : deux reprises indépendantes ne remplacent pas les textes de l’autre onglet',async()=>{const {scope,mod}=fixture(),source=draft();await mod.sauverCycle(scope,source);const a=mod.copierCycle(source),b=mod.copierCycle(source);a.commentaire='Onglet A';b.commentaire='Onglet B';await Promise.all([mod.sauverCycle(scope,a),mod.sauverCycle(scope,b)]);assert.deepEqual(new Set((await mod.lireCycles(scope,ecart)).map(x=>x.commentaire)),new Set([source.commentaire,'Onglet A','Onglet B']));});
test('Correction locale : compte, entreprise et session révoquée restent isolés',async()=>{const {scope,scopes,mod}=fixture(),d=draft();await mod.sauverCycle(scope,d);const other=scopes.activateOfflineScope(crypto.randomUUID(),company);assert.equal((await mod.lireCycles(other,ecart)).length,0);await assert.rejects(mod.lireCycles(scope,ecart));await assert.rejects(mod.sauverCycle(other,d));const org=scopes.activateOfflineScope(user,crypto.randomUUID());assert.equal((await mod.lireCycles(org,ecart)).length,0);const back=scopes.activateOfflineScope(user,company);assert.equal((await mod.lireCycles(back,ecart)).length,1);});
test('Correction locale : ordre des frappes et écriture acceptée avant verrouillage',async()=>{const {scope,scopes,mod}=fixture(),d=draft(),writer=new mod.EcrivainCycle(scope);const a=writer.save({...d,commentaire:'Premier'}),b=writer.save({...d,commentaire:'Dernier'});scopes.deactivateOfflineScope();await Promise.all([a,b]);assert.throws(()=>writer.save(d));const back=scopes.activateOfflineScope(user,company);assert.equal((await mod.lireCycles(back,ecart))[0].commentaire,'Dernier');});
test('Correction locale : échec de stockage ne donne pas de feu vert réseau et préserve la copie précédente',async()=>{const {scope,mod}=fixture(),d=draft(),writer=new mod.EcrivainCycle(scope);await writer.save(d);const original=IDBObjectStore.prototype.put;let sends=0;IDBObjectStore.prototype.put=function(){throw new DOMException('Plein','QuotaExceededError')};try{await assert.rejects(writer.save({...d,commentaire:'Changement'}).then(()=>sends++));assert.equal(sends,0);}finally{IDBObjectStore.prototype.put=original;}assert.equal((await mod.lireCycles(scope,ecart))[0].commentaire,d.commentaire);await writer.save({...d,commentaire:'Nouvel essai'});assert.equal((await mod.lireCycles(scope,ecart))[0].commentaire,'Nouvel essai');});
