const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {Readable}=require('node:stream');const mod=require('../scripts/backup/storage.cjs');
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'storage-backup-test-')),key=crypto.randomBytes(32);let changed=false,denied=false;const content=Buffer.from('%PDF-fichier fictif privé');const rows=[{name:'preuve.pdf',id:'id-test',metadata:{size:content.length},updated_at:'2026-09-15'}];let scans=0;
const client={storage:{
 listBuckets:async()=>({data:[{id:'test',public:false}],error:null}),
 from:()=>({
  list:async(prefix)=>{if(denied)return{error:{message:'refus'}};if(prefix==='')return{data:[{name:'dossier',id:null}]};scans++;return{data:rows.map(r=>({...r,updated_at:changed&&scans>1?'nouvelle-version':r.updated_at}))}},
  download:()=>({asStream:async()=>({data:new ReadableStream({start(c){c.enqueue(content);c.close();}}),error:null})})
 })
}};
return{root,key,client,content,changed:()=>changed=true,denied:()=>denied=true};}
test('Sauvegarde : fichiers et manifeste chiffrés, restauration des octets sans réseau',async()=>{const f=await fixture();try{const dir=path.join(f.root,'backup'),out=path.join(f.root,'restore');assert.deepEqual(await mod.backup(f.client,dir,f.key,'test'),{count:1,bytes:f.content.length});assert.equal((await fs.readFile(path.join(dir,'manifest.enc'))).includes(Buffer.from('preuve.pdf')),false);f.denied();assert.deepEqual(await mod.restore(dir,out,f.key),{count:1,bytes:f.content.length});const manifest=JSON.parse(await fs.readFile(path.join(out,'manifest.json')));assert.equal(manifest.files[0].name,'dossier/preuve.pdf');assert.deepEqual(await fs.readFile(path.join(out,mod.filename('test','dossier/preuve.pdf').replace('.enc','.bin'))),f.content);assert.equal((await fs.stat(dir)).mode&0o777,0o700);}finally{await fs.rm(f.root,{recursive:true,force:true})}});
test('Sauvegarde : un inventaire modifié ne produit pas de reçu de succès',async()=>{const f=await fixture();try{f.changed();const dir=path.join(f.root,'backup');await assert.rejects(mod.backup(f.client,dir,f.key,'test'),/changé/);await assert.rejects(fs.access(path.join(dir,'receipt.json')));}finally{await fs.rm(f.root,{recursive:true,force:true})}});
test('Sauvegarde : refus d’inventaire préserve une destination existante',async()=>{const f=await fixture();try{f.denied();await assert.rejects(mod.backup(f.client,f.root,f.key,'test'),/indisponible/);assert.deepEqual(await fs.readdir(f.root),[]);}finally{await fs.rm(f.root,{recursive:true,force:true})}});
test('Restauration : mauvaise clé et chiffrement altéré sont refusés sans fichier validé',async()=>{const f=await fixture();try{const dir=path.join(f.root,'backup');await mod.backup(f.client,dir,f.key,'test');await assert.rejects(mod.restore(dir,path.join(f.root,'badkey'),crypto.randomBytes(32)));const file=path.join(dir,mod.filename('test','dossier/preuve.pdf'));const bytes=await fs.readFile(file);bytes[0]^=1;await fs.writeFile(file,bytes);const out=path.join(f.root,'altered');await assert.rejects(mod.restore(dir,out,f.key));await assert.rejects(fs.access(path.join(out,'VERIFIED.json')));}finally{await fs.rm(f.root,{recursive:true,force:true})}});
test('Restauration : aucun écrasement ni effacement d’une destination existante',async()=>{const f=await fixture();try{const src=path.join(f.root,'source.enc'),target=path.join(f.root,'existing');const meta=await mod.encrypt(Readable.from([f.content]),src,f.key,1000);await fs.writeFile(target,'conserver');await assert.rejects(mod.decrypt(src,target,f.key,meta,1000));assert.equal(await fs.readFile(target,'utf8'),'conserver');}finally{await fs.rm(f.root,{recursive:true,force:true})}});
test('Sauvegarde : flux supérieur à la taille autorisée et clé invalide refusés',async()=>{const f=await fixture();try{await assert.rejects(mod.encrypt(Readable.from([f.content]),path.join(f.root,'large'),f.key,2),/Limite/);await assert.rejects(mod.encrypt(Readable.from([f.content]),path.join(f.root,'key'),Buffer.alloc(2),100));}finally{await fs.rm(f.root,{recursive:true,force:true})}});
