-- 043: Non-conformité créée depuis une annotation de comparaison de plans
--
-- Jusqu'ici, toute NC dérivait d'une réponse de checklist (`ecarts.reponse_id`
-- NOT NULL). Une NC issue d'une annotation de plan n'a ni visite ni réponse :
-- la colonne devient donc nullable. Audit des consommateurs : le rapport de
-- visite et le PDF filtrent par identifiants de réponses connus (ces NC en sont
-- correctement exclues) ; le tableau de bord tolère déjà l'absence de
-- correspondance et les range sous « Sans thème » ; l'export XLSX les traite
-- génériquement.

ALTER TABLE ecarts ALTER COLUMN reponse_id DROP NOT NULL;

-- Numéro lisible : les NC existantes en reçoivent un par ordre de création.
ALTER TABLE ecarts
    ADD COLUMN IF NOT EXISTS numero integer GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ecarts
    ADD COLUMN IF NOT EXISTS titre    text,
    ADD COLUMN IF NOT EXISTS type     text,
    ADD COLUMN IF NOT EXISTS priorite text;

ALTER TABLE ecarts DROP CONSTRAINT IF EXISTS ecarts_type_check;
ALTER TABLE ecarts ADD CONSTRAINT ecarts_type_check
    CHECK (type IS NULL OR type IN ('ecart_plan'));

ALTER TABLE ecarts DROP CONSTRAINT IF EXISTS ecarts_priorite_check;
ALTER TABLE ecarts ADD CONSTRAINT ecarts_priorite_check
    CHECK (priorite IS NULL OR priorite IN ('haute', 'moyenne', 'basse'));

-- Une NC issue d'une annotation doit rester rattachable à son origine
ALTER TABLE ecarts DROP CONSTRAINT IF EXISTS ecarts_origine_check;
ALTER TABLE ecarts ADD CONSTRAINT ecarts_origine_check
    CHECK (reponse_id IS NOT NULL OR type = 'ecart_plan');

CREATE TABLE comparaison_nc_links (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    annotation_id uuid        NOT NULL REFERENCES comparaison_annotations(id) ON DELETE CASCADE,
    nc_id         uuid        NOT NULL REFERENCES ecarts(id) ON DELETE CASCADE,
    capture_url   text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (annotation_id, nc_id)
);

CREATE INDEX idx_comparaison_nc_links_annotation ON comparaison_nc_links(annotation_id);
CREATE INDEX idx_comparaison_nc_links_nc ON comparaison_nc_links(nc_id);

ALTER TABLE comparaison_nc_links ENABLE ROW LEVEL SECURITY;

-- Même périmètre que les annotations : inspecteur assigné au chantier ou admin
CREATE POLICY nc_links_select ON comparaison_nc_links
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM comparaison_annotations a
            JOIN comparaisons c ON c.id = a.comparaison_id
            WHERE a.id = comparaison_nc_links.annotation_id
              AND (
                  EXISTS (
                      SELECT 1 FROM chantier_inspecteurs ci
                      WHERE ci.chantier_id = c.chantier_id
                        AND ci.inspecteur_id = auth.uid()
                  )
                  OR public.user_role() = 'administrateur'
              )
        )
    );

CREATE POLICY nc_links_insert ON comparaison_nc_links
    FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM comparaison_annotations a
            JOIN comparaisons c ON c.id = a.comparaison_id
            WHERE a.id = comparaison_nc_links.annotation_id
              AND (
                  EXISTS (
                      SELECT 1 FROM chantier_inspecteurs ci
                      WHERE ci.chantier_id = c.chantier_id
                        AND ci.inspecteur_id = auth.uid()
                  )
                  OR public.user_role() = 'administrateur'
              )
        )
    );

CREATE POLICY nc_links_delete ON comparaison_nc_links
    FOR DELETE TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM comparaison_annotations a
            JOIN comparaisons c ON c.id = a.comparaison_id
            WHERE a.id = comparaison_nc_links.annotation_id
              AND (
                  EXISTS (
                      SELECT 1 FROM chantier_inspecteurs ci
                      WHERE ci.chantier_id = c.chantier_id
                        AND ci.inspecteur_id = auth.uid()
                  )
                  OR public.user_role() = 'administrateur'
              )
        )
    );

COMMENT ON COLUMN ecarts.reponse_id IS 'Réponse de checklist à l''origine de la NC ; NULL pour une NC issue d''une comparaison de plans';
COMMENT ON COLUMN ecarts.numero IS 'Numéro lisible de la NC, affiché sous la forme NC #123';
COMMENT ON COLUMN ecarts.type IS 'ecart_plan pour une NC issue d''une comparaison de plans ; NULL pour une NC de checklist';
COMMENT ON TABLE comparaison_nc_links IS 'Lien entre une annotation de comparaison et la non-conformité qu''elle a produite';
